# Generated by Django 5.0 on 2025-10-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_name', models.CharField(default=None, max_length=255, null=True, verbose_name='Наименование последовательности')),
                ('is_active', models.BooleanField(default=False, verbose_name='Последовательность активна')),
                ('digits_number', models.IntegerField(verbose_name='Количество знаков(длина последовательности)')),
                ('current_number', models.IntegerField(null=True, verbose_name='Текущее значение')),
            ],
            options={
                'verbose_name': 'Последовательность нумерации',
                'verbose_name_plural': 'Последовательности нумерации',
            },
        ),
    ]
