# Generated by Django 5.0 on 2025-05-11 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sequence_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sequences', verbose_name='Вид последовательности'),
        ),
    ]
