# Generated by Django 5.0 on 2025-05-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_orders_sequence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tube_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tubetype', verbose_name='Тип пробирки'),
        ),
        migrations.CreateModel(
            name='Tube_qty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tube_qty', models.IntegerField(default=1, null=True, verbose_name='Количество')),
                ('order_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.orders', verbose_name='Номер заказа')),
                ('tube_type_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tubetype', verbose_name='Вид пробирки')),
            ],
            options={
                'verbose_name': 'Пробирки в заказе',
                'verbose_name_plural': 'Пробирки в заказе',
            },
        ),
    ]
