# Generated by Django 5.0 on 2025-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_orders_tube_type_tube_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='json',
            field=models.JSONField(default=None, null=True, verbose_name='JSON'),
        ),
    ]
