# Generated by Django 5.0 on 2025-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_orders_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tubes',
            field=models.ManyToManyField(to='users.tube_qty'),
        ),
    ]
