# Generated by Django 5.0 on 2025-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_orders_tubes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
