# Generated by Django 5.0 on 2025-05-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_orders_create_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='barcode_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='barcode_type',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='json',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='tube_type',
        ),
    ]
