# Generated by Django 5.0 on 2025-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_orders_barcode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_tubes_qty',
            field=models.IntegerField(default=0, null=True, verbose_name='Пробирок в заказе'),
        ),
    ]
