# Generated by Django 5.0 on 2025-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_orders_total_tubes_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubetype',
            name='tray_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер лотка'),
        ),
    ]
