# Generated by Django 5.0 on 2025-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tubetype_tray_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, null=True, verbose_name='Тело ответа')),
            ],
            options={
                'verbose_name': 'Данные запросов POST',
                'verbose_name_plural': 'Данные запросов POST',
            },
        ),
    ]
