# Generated by Django 5.0 on 2025-06-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_task_source_and_tube_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tubes',
        ),
    ]
