# Generated by Django 5.0 on 2025-05-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_fix_tube_qty_null_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tubes',
        ),
    ]
