# Generated by Django 5.0 on 2025-06-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_fix_tube_qty_null_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='Наименование источника')),
            ],
            options={
                'verbose_name': 'Источник заданий',
                'verbose_name_plural': 'Источники заданий',
            },
        ),
        migrations.AddField(
            model_name='robo7task',
            name='task_source',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.task_source', verbose_name='Источник задания'),
        ),
    ]
