# Generated by Django 5.0 on 2025-10-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_orders_tubes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequences',
            name='sequence_name',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Наименование последовательности'),
        ),
    ]
