# Generated by Django 5.0 on 2025-10-10 17:04

from django.db import migrations


def create_initial_tube_types(apps, schema_editor):
    """Create initial TubeType objects"""
    TubeType = apps.get_model('users', 'TubeType')
    
    # Define the initial tube types
    initial_tube_types = [
        {
            'volume': '5ml',
            'color': 'Красная',
            'filler': 'Без наполнителя',
            'tray_num': 1
        },
        {
            'volume': '3ml',
            'color': 'Синяя',
            'filler': 'Цитрат натрия',
            'tray_num': 2
        },
        {
            'volume': '2ml',
            'color': 'Фиолетовая',
            'filler': 'ЭДТА',
            'tray_num': 3
        },
        {
            'volume': '4ml',
            'color': 'Зеленая',
            'filler': 'Гепарин',
            'tray_num': 4
        },
        {
            'volume': '6ml',
            'color': 'Желтая',
            'filler': 'СЭК',
            'tray_num': 5
        },
        {
            'volume': '1ml',
            'color': 'Серая',
            'filler': 'Фторид натрия',
            'tray_num': 6
        },
        {
            'volume': '8ml',
            'color': 'Оранжевая',
            'filler': 'Тромбин',
            'tray_num': 7
        },
        {
            'volume': '10ml',
            'color': 'Белая',
            'filler': 'Без наполнителя',
            'tray_num': 8
        }
    ]
    
    # Create TubeType objects
    for tube_data in initial_tube_types:
        TubeType.objects.get_or_create(
            volume=tube_data['volume'],
            color=tube_data['color'],
            filler=tube_data['filler'],
            defaults={'tray_num': tube_data['tray_num']}
        )


def reverse_create_initial_tube_types(apps, schema_editor):
    """Reverse the creation of initial TubeType objects"""
    TubeType = apps.get_model('users', 'TubeType')
    
    # Define the tube types to remove
    initial_tube_types = [
        {'volume': '5ml', 'color': 'Красная', 'filler': 'Без наполнителя'},
        {'volume': '3ml', 'color': 'Синяя', 'filler': 'Цитрат натрия'},
        {'volume': '2ml', 'color': 'Фиолетовая', 'filler': 'ЭДТА'},
        {'volume': '4ml', 'color': 'Зеленая', 'filler': 'Гепарин'},
        {'volume': '6ml', 'color': 'Желтая', 'filler': 'СЭК'},
        {'volume': '1ml', 'color': 'Серая', 'filler': 'Фторид натрия'},
        {'volume': '8ml', 'color': 'Оранжевая', 'filler': 'Тромбин'},
        {'volume': '10ml', 'color': 'Белая', 'filler': 'Без наполнителя'}
    ]
    
    # Remove TubeType objects
    for tube_data in initial_tube_types:
        TubeType.objects.filter(
            volume=tube_data['volume'],
            color=tube_data['color'],
            filler=tube_data['filler']
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_sequences_sequence_name'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_tube_types,
            reverse_create_initial_tube_types,
        ),
    ]
